---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: photon-db
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: photon-db
        image: ghcr.io/bikehopper/photon-db:latest
        env:
        - name: BUCKET_NAME
          value: photon-staging
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: build-photon-db
spec:
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
          - name: photon-db
            image: ghcr.io/bikehopper/photon-db-nominatim-importer:latest
            env:
            - name: BUCKET_NAME
              value: photon-staging
