apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-photon-db
spec:
  schedule: "*/15 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: updater-photon-db
            image: curlimages/curl
            command: ["sh", "-c", "curl -vvvv http://$(PHOTON_SVC_NAME).$(POD_NAMESPACE)/nominatim-update"]
            resources:
              requests:
                memory: "10Mi"
                cpu: "50m"
            env:
            - name: PHOTON_SVC_NAME
              value: photon-db-svc
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

