---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: photon-db
  labels:
    app: photon-db
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: photon-db
  template:
    metadata:
      labels:
        app: photon-db
    spec:
      containers:
      - name: photon-db
        ports:
          - containerPort: 2322
        resources:
          requests:
            memory: "1Gi"
            cpu: "1500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        readinessProbe:
          httpGet:
            path: /api?q=healthz
            port: 2322
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 20
        envFrom:
        - secretRef:
            name: minio-photon
        env:
        - name: MINIO_HOST
          value: http://minio.techlabor.org:9000
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      imagePullSecrets:
      - name: dockerconfigjson-github-com
---
apiVersion: v1
kind: Service
metadata:
  name: photon-db-svc
spec:
  type: ClusterIP
  selector:
    app: photon-db
  ports:
  - port: 80
    targetPort: 2322
    protocol: TCP
    name: http
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: build-photon-db
spec:
  schedule: "0 2,14 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: photon-db
            resources:
              requests:
                memory: "3Gi"
                cpu: "3000m"
            envFrom:
            - secretRef:
                name: minio-photon
            env:
            - name: MINIO_HOST
              value: http://minio.techlabor.org:9000
            - name: NOMINATIM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nominatim-db
                  key: password
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          imagePullSecrets:
          - name: dockerconfigjson-github-com
          restartPolicy: Never
